/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    docs: [
        {
            type: 'category',
            label: 'demo',
            collapsible: false,
            collapsed: false,
            items: ['components/index'],//todo sidebar doc切换情况下保持存在
        },
        {
            type: 'category',
            label: '组件属性',
            collapsible: false,
            collapsed: false,
            items: ['components/button/use'],//todo sidebar doc切换情况下保持存在
        },
    ],
    cli: [
        {
            type: 'category',
            label: 'Getting Started',
            collapsible: false,
            collapsed: false,
            items: ['cli/index'],
        },

    ]
};

module.exports = sidebars;
