const fetch = require('node-fetch');
const fs = require('fs');

const path = require('path');

/**
 *
 * This script will create the autogenerated MDX files for each component.
 *
 * Creates files for:
 * - Props
 * - Events
 * - Methods
 * - Slots
 * - others
 * The auto-generated directory & files should be gitignored, since they are created from the published https://teststatic.dmall.com/kayak-project/cabinx/cabinXCore/dist/cabinXAPI@core.json
 * and should never be edited manually.
 */

( async function () {
  const response = await fetch('https://teststatic.dmall.com/kayak-project/cabinx/cabinXCore/dist/cabinXAPI@core.json');
  const components = await response.json();
  
  components.forEach((comp) => {
    const compTag = comp.name;
    const children = comp.children;
    children.forEach((el) => {
      writeAutoGeneratedPage(compTag, el.name, renderProperties(el.children));
    })
  });
} )();

function writeAutoGeneratedPage(componentTag, fileName, data) {
  const dir = `./static/auto-generated/${componentTag}`;
  const path = `${dir}/${fileName}.md`;
  fs.mkdirSync(dir, {recursive: true});
  fs.writeFileSync(path, data);
}

function renderProperties({keyList, children}) {
  // 造table head
  let tableMd = '|';
  let tableHead = '|'
  for ( let i = 0; i < keyList.length; i++ ) {
    const th = keyList[ i ].name;
    tableMd += `${th}|`
    tableHead += `----|`
  }
  tableMd += '\n';
  tableMd += tableHead + '\n'
  children.forEach((el) => {
    tableMd += `|${el.join('|')}|\n`
  })
  return tableMd
}
